// eslint-disable-next-line
export default {
  products: [
    {
      id: 1,
      image: "/images/crop2.jpeg",
      name: "Crop Tops",
      category: "Tops",
      price: 650,
      brand: "Monte Carlo",
      rating: 4.0,
      numReviews: 19,
      count: 19,
    },
    {
      id: 2,
      image: "/images/jeans1.jpg",
      name: "Jeans",
      category: "jeans",
      price: 1050,
      brand: "Levi's",
      rating: 4.5,
      numReviews: 10,
      count: 19,
    },
    {
      id: 3,
      image: "/images/jumpsuit5.webp",
      name: "Jumpsuit",
      category: "jumpsuit",
      price: 1650,
      brand: "Allen",
      rating: 4.5,
      numReviews: 10,
      count: 19,
    },
    {
      id: 4,
      image: "/images/d1.jpg",
      name: "Crop Tops",
      category: "Tops",
      price: 650,
      brand: "Monte Carlo",
      rating: 4.5,
      numReviews: 10,
      count: 5,
    },
    {
      id: 5,
      image: "/images/jeans2.jpeg",
      name: "Jeans",
      category: "Jeans",
      price: 1650,
      brand: "Blissclub",
      rating: 4.5,
      numReviews: 10,
      count: 19,
    },
    {
      id: 6,
      image: "/images/jumpsuit1.jpeg",
      name: "Jumpsuit",
      category: "jumpsuit",
      price: 950,
      brand: "Madame",
      rating: 4.5,
      numReviews: 10,
      count: 5,
    },
    {
      id: 7,
      image: "/images/shorts1.webp",
      name: "Shorts",
      category: "shorts",
      price: 750,
      brand: "Monte Carlo",
      rating: 4.5,
      numReviews: 10,
      count: 19,
    },
    {
      id: 8,
      image: "/images/jeans3.jpeg",
      name: "Jeans",
      category: "jeans",
      price: 650,
      brand: "Blissclub",
      rating: 4.5,
      numReviews: 10,
      count: 19,
    },
    {
      id: 9,
      image: "/images/jumpsuit2.jpeg",
      name: "Jumpsuit",
      category: "jumpsuit",
      price: 1150,
      brand: "Allen",
      rating: 4.4,
      numReviews: 10,
      count: 19,
    },
    {
      id: 10,
      image: "/images/shorts2.jpeg",
      name: "shorts",
      category: "shorts",
      price: 650,
      brand: "Monte Carlo",
      rating: 4.5,
      numReviews: 10,
      count: 19,
    },
    {
      id: 11,
      image: "/images/jeans4.jpeg",
      name: "Jeans",
      category: "jeans",
      price: 650,
      brand: "Levi's",
      rating: 4.5,
      numReviews: 10,
      count: 19,
    },
    {
      id: 12,
      image: "/images/jumpsuit3.jpeg",
      name: "Jumpsuit",
      category: "jumpsuit",
      price: 1860,
      brand: "Madame",
      rating: 4.5,
      numReviews: 10,
      count: 5,
    },
    {
      id: 13,
      image: "/images/crop3.jpeg",
      name: "Crop Tops",
      category: "Tops",
      price: 1650,
      brand: "Monte Carlo",
      rating: 4.5,
      numReviews: 10,
      count: 5,
    },
    {
      id: 14,
      image: "/images/shorts3.jpeg",
      name: "Shorts",
      category: "shorts",
      price: 880,
      brand: "Flying machine",
      rating: 4.8,
      numReviews: 28,
      count: 5,
    },
    {
      id: 15,
      image: "/images/jumpsuit6.webp",
      name: "Jumpsuit",
      category: "jumpsuit",
      price: 990,
      brand: "Linen",
      rating: 4.5,
      numReviews: 10,
      count: 5,
    },
    {
      id: 16,
      image: "/images/shorts4.jpeg",
      name: "Shorts",
      category: "shorts",
      price: 4050,
      brand: "H&M",
      rating: 5.0,
      numReviews: 36,
      count: 5,
    },
    {
      id: 17,
      image: "/images/crop4.jpeg",
      name: "Crop Tops",
      category: "Tops",
      price: 450,
      brand: "Monte Carlo",
      rating: 4.1,
      numReviews: 20,
      count: 5,
    },
    {
      id: 18,
      image: "/images/jumpsuit4.jpeg",
      name: "Jumpsuit",
      category: "jumpsuit",
      price: 1150,
      brand: "Madame",
      rating: 4.6,
      numReviews: 60,
      count: 5,
    },
    {
      id: 19,
      image: "/images/shorts5.jpeg",
      name: "Shorts",
      category: "shorts",
      price: 750,
      brand: "Monte Carlo",
      rating: 4.5,
      numReviews: 10,
      count: 5,
    },
  ],
};
